"""update db

Revision ID: 42f5cfde7e3b
Revises: f7d611f80529
Create Date: 2024-02-18 18:23:19.194913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f5cfde7e3b'
down_revision = 'f7d611f80529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'store', ['id'])
    op.create_unique_constraint(None, 'store__address', ['id'])
    op.create_unique_constraint(None, 'user__address', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user__address', type_='unique')
    op.drop_constraint(None, 'store__address', type_='unique')
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
